### ISSUE TITLE
"More" link in top navigation can't be accessed without JS

### ISSUE THREAD

**Issue by fofr** [alphagov/whitehall#3406]
When Javascript fails – eg SRI hash not accepted, network failure, JS blocked, the "More" link in the Whitehall navigation won't open and reveal the links behind it. This blocks users from completing their tasks.

https://govuk.zendesk.com/agent/tickets/2312982

![screen shot 2017-08-15 at 14 22 52](https://user-images.githubusercontent.com/319055/29317737-406b7b08-81c5-11e7-8a32-80a01d74f0ed.png)

**Comment by thomasleese** [comment]
Has also happened in https://govuk.zendesk.com/agent/tickets/2446037

**Comment by fofr** [comment]
@h-lame Did Whitehall admin disable SRI attributes in the end?

**Comment by fofr** [comment]
"More" should probably link to a page that shows those navigation options. Then JS can prevent that link from triggering and show the dropdown for users with working JS.

**Comment by gpeng** [comment]
The ticket to fix this this is on our doing board. https://trello.com/c/2wYn3eJi/202-new-document-tab-does-not-display-dropdown (well, it's actually the new document tab but it's the same problem). Would be good to discuss/pair @fofr.

**Comment by h-lame** [comment]
@fofr I haven't removed SRI from the admin template, and it doesn't look like anyone else has either.

If it's causing lots of problems because of publishers working on networks that are monkeying around with the assets then removing SRI (even though it's doing its job properly!) seems like a pragmatic workaround for the problem.  It'd be good to couple that with a spike/reivew to work out the scale of the problem as I suspect it's not just the more tab or new document tab.  I wouldn't be surprised if large parts of whitehall admin were not progressively enhanced at all, so fixing just the bits that have been reported won't be enough.  Once we've completed that review and fixed any problems we find we *should* be safe to re-introduce SRI safe in the knowledge that any monkeying about with the assets will be blocked, but also the publishers will still be able to get their work done.

**Comment by fofr** [comment]
@h-lame Completely agree. Suggested to @gpeng that we audit Whitehall for JS only features.

**Comment by gpeng** [comment]
On the backlog :+1: https://trello.com/c/Ly0hzsOT/1098-some-functionality-in-whitehall-admin-doesnt-work-at-all-without-javascript

**Comment by ChrisBAshton** [comment]
The More link has now been a hyperlink for some time, and has its own dedicated page.
